services:
  app:
    env_file:
      - .env
      - .env.app
      - .env.app.production

  cron:
    env_file:
      - .env
      - .env.app
      - .env.app.production

#  web:
#    ports:
#      - "127.0.0.1:80:80"
